version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    user: '1000'
    image: node
    volumes:
      - ./server:/app
    command: ["npm", "start"]
    working_dir: /app
    depends_on:
      - db
    ports:
      - "5000:5000"
